version: '3.6'
services:
  nhp-server:
    image: rajnish2198/nasa-planets:latest
    restart: always
    pull_policy: always
    ports:
      - 8000:8000
    container_name: nhp-server
#   caddy:
#     image: rajnish2198/nasa-planets-caddy
#     restart: unless-stopped
#     depends_on:
#       - nhp-server
#     ports:
#       - 80:80
#       - 443:443
#       - 2019:2019
#     volumes:
#       caddy_data:/data
#       caddy_config:/config

# volumes:
#   caddy_data:
#   caddy_config: