name: NASA Project CI
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    step: 
      - uses: actions/checkout@3
      - uses: actions/setup-node@v3
        with:
        node-version: '20'
      - run: npm install
      - run: npm run build --prefix client